# Generated by Django 3.1.2 on 2020-10-14 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid_nome', models.CharField(max_length=100, verbose_name='Cidade:')),
            ],
        ),
        migrations.CreateModel(
            name='Cnh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CNH:')),
                ('cnh_categoria', models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'AB'), (6, 'AC'), (7, 'AD'), (8, 'AE')], null=True, verbose_name='Categoria:')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade:')),
                ('cnh_condutor_emergencia', models.BooleanField(verbose_name='Condutor de Emergência?')),
                ('cnh_ultimo_cve', models.DateField(blank=True, null=True, verbose_name='Data do Último CVE:')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_logradouro', models.CharField(max_length=200, verbose_name='Logradouro:')),
                ('end_numero', models.CharField(max_length=10, verbose_name='Número:')),
                ('end_complemento', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Complemento:')),
                ('end_bairro', models.CharField(max_length=100, verbose_name='Bairro:')),
                ('end_cep', models.CharField(max_length=100, verbose_name='CEP:')),
                ('end_cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcs.cidade', verbose_name='Cidade:')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gra_grau', models.CharField(max_length=200, verbose_name='Grau:')),
                ('gra_simbolo', models.ImageField(blank=True, null=True, upload_to='graduacao_pictures/', verbose_name='Símbolo:')),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_nome', models.CharField(max_length=100, verbose_name='Estado:')),
                ('uf_sigla', models.CharField(default='SC', max_length=2, verbose_name='Sigla:')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nome', models.CharField(max_length=200, verbose_name='Nome Completo:')),
                ('usu_foto', models.ImageField(blank=True, upload_to='usuario_pictures/', verbose_name='Foto de Perfil:')),
                ('usu_data_de_nascimento', models.DateField(verbose_name='Data de Nascimento:')),
                ('usu_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Não declarado')], max_length=1, verbose_name='Sexo:')),
                ('usu_naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade:')),
                ('usu_cpf', models.CharField(max_length=100, verbose_name='CPF:')),
                ('usu_rg', models.CharField(max_length=100, verbose_name='RG:')),
                ('usu_filiacao', models.CharField(max_length=600, verbose_name='Filiação:')),
                ('usu_estado_civil', models.IntegerField(blank=True, choices=[(0, 'Solteiro (a)'), (1, 'Casado (a)'), (2, 'Divorciado (a)'), (3, 'Separado (a)'), (4, 'Viúvo (a)'), (5, 'Outro')], null=True, verbose_name='Estado civil:')),
                ('usu_numero_filhos', models.IntegerField(verbose_name='Número de Filhos:')),
                ('usu_telefone', models.CharField(max_length=100, verbose_name='Telefone:')),
                ('usu_whatsapp', models.CharField(max_length=100, verbose_name='WhatsApp:')),
                ('usu_telefone_residencial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone Residêncial:')),
                ('usu_email', models.EmailField(max_length=254, verbose_name='E-mail:')),
                ('usu_escolaridade', models.IntegerField(blank=True, choices=[(0, 'Ensino Fundamental Incompleto'), (1, 'Ensino Fundamental Completo'), (2, 'Ensino Médio Incompleto'), (3, 'Ensino Médio Completo'), (4, 'Ensino Superior Incompleto'), (5, 'Ensino Superior Completo')], null=True, verbose_name='Escolaridade:')),
                ('usu_area_de_formacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área de Formação:')),
                ('usu_facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook:')),
                ('usu_instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram:')),
                ('usu_is_adm', models.BooleanField(default=False, verbose_name='Administrador do sistema?')),
                ('usu_data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usu_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usu_endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcs.endereco', verbose_name='Endereço:')),
                ('usu_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário:')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_nome', models.CharField(max_length=100, verbose_name='Local:')),
                ('unidade_descricao', models.CharField(max_length=200, verbose_name='Descrição:')),
                ('unidade_foto', models.ImageField(blank=True, upload_to='usuario_pictures/', verbose_name='Foto do Local:')),
                ('unidade_rbm', models.CharField(choices=[('1ª Região', '1ª Região'), ('2ª Região', '2ª Região'), ('3ª Região', '3ª Região')], max_length=20, verbose_name='RBM (Região de Bombeiro Militar):')),
                ('unidade_bbm', models.CharField(choices=[('1º BBM', '1º BBM'), ('2º BBM', '2º BBM'), ('3º BBM', '3º BBM'), ('4º BBM', '4º BBM'), ('5º BBM', '5º BBM'), ('6º BBM', '6º BBM'), ('7º BBM', '7º BBM'), ('8º BBM', '8º BBM'), ('9º BBM', '9º BBM'), ('10º BBM', '10º BBM'), ('11º BBM', '11º BBM'), ('12º BBM', '12º BBM'), ('13º BBM', '13º BBM'), ('14º BBM', '14º BBM'), ('15º BBM', '15º BBM')], max_length=20, verbose_name='BBM (Batalhão de Bombeiro Militar):')),
                ('unidade_endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcs.endereco', verbose_name='Endereço:')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_nome', models.CharField(max_length=100, verbose_name='Nome do Familiar:')),
                ('fm_parentesco', models.CharField(max_length=100, verbose_name='Grau de Parentesco:')),
                ('fm_telefone', models.CharField(max_length=100, verbose_name='Telefone:')),
                ('fm_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcs.usuario', verbose_name='Usuário:')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='cid_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.uf', verbose_name='Estado:'),
        ),
        migrations.CreateModel(
            name='Bc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_nome_de_guerra', models.CharField(max_length=200, verbose_name='Nome de Guerra:')),
                ('bc_data_formatura', models.DateField(blank=True, null=True, verbose_name='Data da Formatura:')),
                ('bc_data_ultima_promocao', models.DateField(blank=True, null=True, verbose_name='Data da Última Promoção:')),
                ('bc_situacao', models.BooleanField(default=True, verbose_name='Situação: (ativo/inativo)')),
                ('bc_mergulhador', models.BooleanField(blank=True, null=True, verbose_name='Mergulhador?')),
                ('bc_cnh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcs.cnh', verbose_name='CNH:')),
                ('bc_graduacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.graduacao', verbose_name='Graduação:')),
                ('bc_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcs.usuario', verbose_name='Usuário:')),
            ],
        ),
    ]
