# Generated by Django 3.1.2 on 2020-10-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usu_lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcs.unidade', verbose_name='Lotação:'),
        ),
    ]
