# Generated by Django 3.1.2 on 2020-10-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0002_usuario_usu_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnh',
            name='cnh_categoria',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'AB'), (6, 'AC'), (7, 'AD'), (8, 'AE'), (9, 'Não Informado')], default=9, verbose_name='Categoria:'),
        ),
    ]
